node1: GRAIN_TYPE=Sleep METRICS_PORT=9001 PORT=8091 ./silod 2>&1 > node1.log
node2: GRAIN_TYPE=HelloWorld METRICS_PORT=9002 PORT=8092 ./silod 2>&1 > node2.log
node3: METRICS_PORT=9003 PORT=8093 ./silod 2>&1 > node3.log
