// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: silo/silo.proto

package silo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationStatus int32

const (
	RegistrationStatus_REGISTRATION_OK    RegistrationStatus = 0
	RegistrationStatus_REGISTRATION_ERROR RegistrationStatus = 1
)

// Enum value maps for RegistrationStatus.
var (
	RegistrationStatus_name = map[int32]string{
		0: "REGISTRATION_OK",
		1: "REGISTRATION_ERROR",
	}
	RegistrationStatus_value = map[string]int32{
		"REGISTRATION_OK":    0,
		"REGISTRATION_ERROR": 1,
	}
)

func (x RegistrationStatus) Enum() *RegistrationStatus {
	p := new(RegistrationStatus)
	*p = x
	return p
}

func (x RegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_silo_proto_enumTypes[0].Descriptor()
}

func (RegistrationStatus) Type() protoreflect.EnumType {
	return &file_silo_silo_proto_enumTypes[0]
}

func (x RegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationStatus.Descriptor instead.
func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{0}
}

type PlacementStatus int32

const (
	PlacementStatus_PLACEMENT_OK                 PlacementStatus = 0
	PlacementStatus_PLACEMENT_NO_COMPATIBLE_SILO PlacementStatus = 1
	PlacementStatus_PLACEMENT_ERROR              PlacementStatus = 2
)

// Enum value maps for PlacementStatus.
var (
	PlacementStatus_name = map[int32]string{
		0: "PLACEMENT_OK",
		1: "PLACEMENT_NO_COMPATIBLE_SILO",
		2: "PLACEMENT_ERROR",
	}
	PlacementStatus_value = map[string]int32{
		"PLACEMENT_OK":                 0,
		"PLACEMENT_NO_COMPATIBLE_SILO": 1,
		"PLACEMENT_ERROR":              2,
	}
)

func (x PlacementStatus) Enum() *PlacementStatus {
	p := new(PlacementStatus)
	*p = x
	return p
}

func (x PlacementStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_silo_proto_enumTypes[1].Descriptor()
}

func (PlacementStatus) Type() protoreflect.EnumType {
	return &file_silo_silo_proto_enumTypes[1]
}

func (x PlacementStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementStatus.Descriptor instead.
func (PlacementStatus) EnumDescriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{1}
}

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_OK             ExecutionStatus = 0
	ExecutionStatus_EXECUTION_ERROR          ExecutionStatus = 1
	ExecutionStatus_EXECUTION_NO_LONGER_ABLE ExecutionStatus = 2 // The grain is no longer able to execute
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_OK",
		1: "EXECUTION_ERROR",
		2: "EXECUTION_NO_LONGER_ABLE",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_OK":             0,
		"EXECUTION_ERROR":          1,
		"EXECUTION_NO_LONGER_ABLE": 2,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_silo_proto_enumTypes[2].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_silo_silo_proto_enumTypes[2]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{2}
}

type RegisterReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReminderId string `protobuf:"bytes,1,opt,name=reminderId,proto3" json:"reminderId,omitempty"`
}

func (x *RegisterReminderResponse) Reset() {
	*x = RegisterReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReminderResponse) ProtoMessage() {}

func (x *RegisterReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReminderResponse.ProtoReflect.Descriptor instead.
func (*RegisterReminderResponse) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReminderResponse) GetReminderId() string {
	if x != nil {
		return x.ReminderId
	}
	return ""
}

type RegisterReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrainType    string `protobuf:"bytes,1,opt,name=grainType,proto3" json:"grainType,omitempty"`
	GrainId      string `protobuf:"bytes,2,opt,name=grainId,proto3" json:"grainId,omitempty"`
	ReminderName string `protobuf:"bytes,3,opt,name=reminderName,proto3" json:"reminderName,omitempty"`
	DueTime      int64  `protobuf:"varint,4,opt,name=dueTime,proto3" json:"dueTime,omitempty"`
	Period       int64  `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"`
	Data         []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RegisterReminderRequest) Reset() {
	*x = RegisterReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReminderRequest) ProtoMessage() {}

func (x *RegisterReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReminderRequest.ProtoReflect.Descriptor instead.
func (*RegisterReminderRequest) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReminderRequest) GetGrainType() string {
	if x != nil {
		return x.GrainType
	}
	return ""
}

func (x *RegisterReminderRequest) GetGrainId() string {
	if x != nil {
		return x.GrainId
	}
	return ""
}

func (x *RegisterReminderRequest) GetReminderName() string {
	if x != nil {
		return x.ReminderName
	}
	return ""
}

func (x *RegisterReminderRequest) GetDueTime() int64 {
	if x != nil {
		return x.DueTime
	}
	return 0
}

func (x *RegisterReminderRequest) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *RegisterReminderRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GrainInvocationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string          `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	Status    ExecutionStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=silo.ExecutionStatus" json:"Status,omitempty"`
	// Types that are assignable to TestResult:
	//	*GrainInvocationResult_Result
	//	*GrainInvocationResult_Error
	TestResult isGrainInvocationResult_TestResult `protobuf_oneof:"test_result"`
}

func (x *GrainInvocationResult) Reset() {
	*x = GrainInvocationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrainInvocationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrainInvocationResult) ProtoMessage() {}

func (x *GrainInvocationResult) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrainInvocationResult.ProtoReflect.Descriptor instead.
func (*GrainInvocationResult) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{2}
}

func (x *GrainInvocationResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GrainInvocationResult) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_OK
}

func (m *GrainInvocationResult) GetTestResult() isGrainInvocationResult_TestResult {
	if m != nil {
		return m.TestResult
	}
	return nil
}

func (x *GrainInvocationResult) GetResult() []byte {
	if x, ok := x.GetTestResult().(*GrainInvocationResult_Result); ok {
		return x.Result
	}
	return nil
}

func (x *GrainInvocationResult) GetError() string {
	if x, ok := x.GetTestResult().(*GrainInvocationResult_Error); ok {
		return x.Error
	}
	return ""
}

type isGrainInvocationResult_TestResult interface {
	isGrainInvocationResult_TestResult()
}

type GrainInvocationResult_Result struct {
	Result []byte `protobuf:"bytes,3,opt,name=Result,proto3,oneof"`
}

type GrainInvocationResult_Error struct {
	Error string `protobuf:"bytes,4,opt,name=Error,proto3,oneof"`
}

func (*GrainInvocationResult_Result) isGrainInvocationResult_TestResult() {}

func (*GrainInvocationResult_Error) isGrainInvocationResult_TestResult() {}

type GrainInvocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId  string `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	GrainType  string `protobuf:"bytes,2,opt,name=GrainType,proto3" json:"GrainType,omitempty"`
	GrainId    string `protobuf:"bytes,3,opt,name=GrainId,proto3" json:"GrainId,omitempty"`
	MethodName string `protobuf:"bytes,4,opt,name=MethodName,proto3" json:"MethodName,omitempty"`
	Data       []byte `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GrainInvocationRequest) Reset() {
	*x = GrainInvocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrainInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrainInvocationRequest) ProtoMessage() {}

func (x *GrainInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrainInvocationRequest.ProtoReflect.Descriptor instead.
func (*GrainInvocationRequest) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{3}
}

func (x *GrainInvocationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GrainInvocationRequest) GetGrainType() string {
	if x != nil {
		return x.GrainType
	}
	return ""
}

func (x *GrainInvocationRequest) GetGrainId() string {
	if x != nil {
		return x.GrainId
	}
	return ""
}

func (x *GrainInvocationRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *GrainInvocationRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SupportedGrainsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrainTypes []string `protobuf:"bytes,1,rep,name=grainTypes,proto3" json:"grainTypes,omitempty"`
}

func (x *SupportedGrainsResponse) Reset() {
	*x = SupportedGrainsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedGrainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedGrainsResponse) ProtoMessage() {}

func (x *SupportedGrainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedGrainsResponse.ProtoReflect.Descriptor instead.
func (*SupportedGrainsResponse) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{4}
}

func (x *SupportedGrainsResponse) GetGrainTypes() []string {
	if x != nil {
		return x.GrainTypes
	}
	return nil
}

type RegisterGrainHandlerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrainType    string `protobuf:"bytes,1,opt,name=grainType,proto3" json:"grainType,omitempty"`
	GrainVersion string `protobuf:"bytes,2,opt,name=grainVersion,proto3" json:"grainVersion,omitempty"`
}

func (x *RegisterGrainHandlerRequest) Reset() {
	*x = RegisterGrainHandlerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterGrainHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGrainHandlerRequest) ProtoMessage() {}

func (x *RegisterGrainHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGrainHandlerRequest.ProtoReflect.Descriptor instead.
func (*RegisterGrainHandlerRequest) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterGrainHandlerRequest) GetGrainType() string {
	if x != nil {
		return x.GrainType
	}
	return ""
}

func (x *RegisterGrainHandlerRequest) GetGrainVersion() string {
	if x != nil {
		return x.GrainVersion
	}
	return ""
}

type RegisterGrainHandlerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status RegistrationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=silo.RegistrationStatus" json:"status,omitempty"`
}

func (x *RegisterGrainHandlerResponse) Reset() {
	*x = RegisterGrainHandlerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterGrainHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGrainHandlerResponse) ProtoMessage() {}

func (x *RegisterGrainHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGrainHandlerResponse.ProtoReflect.Descriptor instead.
func (*RegisterGrainHandlerResponse) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterGrainHandlerResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_OK
}

type GrainInvocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ExecutionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=silo.ExecutionStatus" json:"status,omitempty"`
	GrainId string          `protobuf:"bytes,2,opt,name=grainId,proto3" json:"grainId,omitempty"`
	Result  []byte          `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GrainInvocationResponse) Reset() {
	*x = GrainInvocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrainInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrainInvocationResponse) ProtoMessage() {}

func (x *GrainInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrainInvocationResponse.ProtoReflect.Descriptor instead.
func (*GrainInvocationResponse) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{7}
}

func (x *GrainInvocationResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_OK
}

func (x *GrainInvocationResponse) GetGrainId() string {
	if x != nil {
		return x.GrainId
	}
	return ""
}

func (x *GrainInvocationResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type PlaceGrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrainType string `protobuf:"bytes,1,opt,name=grainType,proto3" json:"grainType,omitempty"`
	GrainId   string `protobuf:"bytes,2,opt,name=grainId,proto3" json:"grainId,omitempty"`
}

func (x *PlaceGrainRequest) Reset() {
	*x = PlaceGrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceGrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceGrainRequest) ProtoMessage() {}

func (x *PlaceGrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceGrainRequest.ProtoReflect.Descriptor instead.
func (*PlaceGrainRequest) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{8}
}

func (x *PlaceGrainRequest) GetGrainType() string {
	if x != nil {
		return x.GrainType
	}
	return ""
}

func (x *PlaceGrainRequest) GetGrainId() string {
	if x != nil {
		return x.GrainId
	}
	return ""
}

type PlaceGrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   PlacementStatus `protobuf:"varint,1,opt,name=status,proto3,enum=silo.PlacementStatus" json:"status,omitempty"`
	Location string          `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *PlaceGrainResponse) Reset() {
	*x = PlaceGrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceGrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceGrainResponse) ProtoMessage() {}

func (x *PlaceGrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceGrainResponse.ProtoReflect.Descriptor instead.
func (*PlaceGrainResponse) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{9}
}

func (x *PlaceGrainResponse) GetStatus() PlacementStatus {
	if x != nil {
		return x.Status
	}
	return PlacementStatus_PLACEMENT_OK
}

func (x *PlaceGrainResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch int64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_silo_silo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_silo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_silo_silo_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_silo_silo_proto protoreflect.FileDescriptor

var file_silo_silo_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x69, 0x6c, 0x6f, 0x2f, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x69, 0x6c, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x22, 0xbb, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x67, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x75, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x75, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa5,
	0x01, 0x0a, 0x15, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x16, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0d, 0x0a, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x47, 0x72, 0x61, 0x69, 0x6e,
	0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x47, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x17, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x72, 0x61, 0x69, 0x6e,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x50, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x7a, 0x0a, 0x17, 0x47, 0x72, 0x61,
	0x69, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4b, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x47, 0x72,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72,
	0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x22, 0x5f, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x47, 0x72, 0x61, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x2a, 0x41, 0x0a, 0x12, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x13, 0x0a, 0x0f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x2a, 0x5a, 0x0a, 0x0f,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x20, 0x0a, 0x1c, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x4e,
	0x4f, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x54, 0x49, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x49, 0x4c,
	0x4f, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x4d, 0x45, 0x4e, 0x54,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x2a, 0x56, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x45,
	0x58, 0x45, 0x43, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0f, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4e, 0x4f, 0x5f, 0x4c, 0x4f, 0x4e, 0x47, 0x45, 0x52, 0x5f, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02,
	0x32, 0xcf, 0x03, 0x0a, 0x0b, 0x53, 0x69, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x34, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x12, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x47,
	0x72, 0x61, 0x69, 0x6e, 0x12, 0x17, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x49, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e,
	0x47, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x47, 0x72,
	0x61, 0x69, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12,
	0x21, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47,
	0x72, 0x61, 0x69, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x47, 0x72, 0x61, 0x69, 0x6e, 0x49,
	0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x1b, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x47, 0x72, 0x61, 0x69,
	0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x12, 0x53, 0x0a,
	0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x1d, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x73, 0x69, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x6f, 0x68, 0x6e, 0x65, 0x77, 0x61, 0x72, 0x74, 0x2f, 0x67, 0x6f, 0x2d, 0x6f, 0x72,
	0x6c, 0x65, 0x61, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x69, 0x6c, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_silo_silo_proto_rawDescOnce sync.Once
	file_silo_silo_proto_rawDescData = file_silo_silo_proto_rawDesc
)

func file_silo_silo_proto_rawDescGZIP() []byte {
	file_silo_silo_proto_rawDescOnce.Do(func() {
		file_silo_silo_proto_rawDescData = protoimpl.X.CompressGZIP(file_silo_silo_proto_rawDescData)
	})
	return file_silo_silo_proto_rawDescData
}

var file_silo_silo_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_silo_silo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_silo_silo_proto_goTypes = []interface{}{
	(RegistrationStatus)(0),              // 0: silo.RegistrationStatus
	(PlacementStatus)(0),                 // 1: silo.PlacementStatus
	(ExecutionStatus)(0),                 // 2: silo.ExecutionStatus
	(*RegisterReminderResponse)(nil),     // 3: silo.RegisterReminderResponse
	(*RegisterReminderRequest)(nil),      // 4: silo.RegisterReminderRequest
	(*GrainInvocationResult)(nil),        // 5: silo.GrainInvocationResult
	(*GrainInvocationRequest)(nil),       // 6: silo.GrainInvocationRequest
	(*SupportedGrainsResponse)(nil),      // 7: silo.SupportedGrainsResponse
	(*RegisterGrainHandlerRequest)(nil),  // 8: silo.RegisterGrainHandlerRequest
	(*RegisterGrainHandlerResponse)(nil), // 9: silo.RegisterGrainHandlerResponse
	(*GrainInvocationResponse)(nil),      // 10: silo.GrainInvocationResponse
	(*PlaceGrainRequest)(nil),            // 11: silo.PlaceGrainRequest
	(*PlaceGrainResponse)(nil),           // 12: silo.PlaceGrainResponse
	(*PingResponse)(nil),                 // 13: silo.PingResponse
	(*emptypb.Empty)(nil),                // 14: google.protobuf.Empty
}
var file_silo_silo_proto_depIdxs = []int32{
	2,  // 0: silo.GrainInvocationResult.Status:type_name -> silo.ExecutionStatus
	0,  // 1: silo.RegisterGrainHandlerResponse.status:type_name -> silo.RegistrationStatus
	2,  // 2: silo.GrainInvocationResponse.status:type_name -> silo.ExecutionStatus
	1,  // 3: silo.PlaceGrainResponse.status:type_name -> silo.PlacementStatus
	14, // 4: silo.SiloService.Ping:input_type -> google.protobuf.Empty
	11, // 5: silo.SiloService.PlaceGrain:input_type -> silo.PlaceGrainRequest
	6,  // 6: silo.SiloService.InvokeGrain:input_type -> silo.GrainInvocationRequest
	8,  // 7: silo.SiloService.RegisterGrainHandler:input_type -> silo.RegisterGrainHandlerRequest
	5,  // 8: silo.SiloService.ResultStream:input_type -> silo.GrainInvocationResult
	4,  // 9: silo.SiloService.RegisterReminder:input_type -> silo.RegisterReminderRequest
	13, // 10: silo.SiloService.Ping:output_type -> silo.PingResponse
	12, // 11: silo.SiloService.PlaceGrain:output_type -> silo.PlaceGrainResponse
	10, // 12: silo.SiloService.InvokeGrain:output_type -> silo.GrainInvocationResponse
	6,  // 13: silo.SiloService.RegisterGrainHandler:output_type -> silo.GrainInvocationRequest
	14, // 14: silo.SiloService.ResultStream:output_type -> google.protobuf.Empty
	3,  // 15: silo.SiloService.RegisterReminder:output_type -> silo.RegisterReminderResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_silo_silo_proto_init() }
func file_silo_silo_proto_init() {
	if File_silo_silo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_silo_silo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrainInvocationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrainInvocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedGrainsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterGrainHandlerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterGrainHandlerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrainInvocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceGrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceGrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_silo_silo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_silo_silo_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*GrainInvocationResult_Result)(nil),
		(*GrainInvocationResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_silo_silo_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_silo_proto_goTypes,
		DependencyIndexes: file_silo_silo_proto_depIdxs,
		EnumInfos:         file_silo_silo_proto_enumTypes,
		MessageInfos:      file_silo_silo_proto_msgTypes,
	}.Build()
	File_silo_silo_proto = out.File
	file_silo_silo_proto_rawDesc = nil
	file_silo_silo_proto_goTypes = nil
	file_silo_silo_proto_depIdxs = nil
}
